# Generated by Django 4.1 on 2022-11-21 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0004_alter_product_quantity"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productorder",
            old_name="Created_Date",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="productorder",
            old_name="Updated_Date",
            new_name="updated_at",
        ),
        migrations.AddField(
            model_name="cart",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="category",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="productorder",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
