# Generated by Django 4.1 on 2022-11-21 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0006_delete_productorder"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="quantity",
        ),
    ]
