# Generated by Django 4.1 on 2022-11-21 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0007_remove_cart_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="item_quantity",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
